# Generated by Django 2.1.7 on 2019-02-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField(default=None)),
                ('code', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Student name')),
                ('surname', models.CharField(max_length=60, verbose_name='Student surname')),
                ('status', models.BooleanField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('courses', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
